site_name: Popsink documentation
site_url: https://docs.popsink.com/
theme:
  name: material
  logo: assets/logo.svg
  features:
    - header.autohide
  palette: 
    primary: black

plugins:
  - search
  - meta-descriptions
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/crisp.js